services:
  db:
    image: postgres:15
    container_name: avito_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avito_user -d avito_prs"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    command: [
      "-path=/migrations",
      "-database=postgres://avito_user:avito_password@db:5432/avito_prs?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    restart: "on-failure"

  app:
    build: .
    container_name: avito_app
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      APP_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: avito_user
      DB_PASSWORD: avito_password
      DB_NAME: avito_prs
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pg_data:
